export const GET_CLASSES = 'GET_CLASSES';
export const GET_CLASSES_SUCCESS = 'GET_CLASSES_SUCCESS';
export const GET_CLASSES_FAILED = 'GET_CLASSES_FAILED';

export const CREATE_CLASSES = 'CREATE_CLASSES';
export const CREATE_CLASSES_SUCCESS = 'CREATE_CLASSES_SUCCESS';
export const CREATE_CLASSES_FAILED = 'CREATE_CLASSES_FAILED';

export const UPDATE_CLASSES = 'UPDATE_CLASSES';
export const UPDATE_CLASSES_SUCCESS = 'UPDATE_CLASSES_SUCCESS';
export const UPDATE_CLASSES_FAILED = 'UPDATE_CLASSES_FAILED';

export const DELETE_CLASSES = 'DELETE_CLASSES';
export const DELETE_CLASSES_SUCCESS = 'DELETE_CLASSES_SUCCESS';
export const DELETE_CLASSES_FAILED = 'DELETE_CLASSES_FAILED';
